### PR TITLE
Send error code to client to refer to traceback in log

### LINKED ISSUE #503: Unique tags for error reports
Instead of sending tracebacks to the client (which may be a security risk), record the traceback in the log, tag it with a unique label, and send the label to the client (so the client can later identify the traceback to a site administrator).

### PR DESCRIPTION
**Pull request by ronichoudhury**
Closes #503

### CODE REVIEW

**Comment by manthey** [comment]
This could use a test.

**Comment by ronichoudhury** [comment]
I thought about it but it didn't seem critical to test this feature, but it's not a bad idea. I'll add one today.

**Comment by ronichoudhury** [comment]
@manthey I added a test, please take a look

**Comment by manthey** [comment]
LGTM

**Pull request merged**
