### PR TITLE
Reporting missing traceback

### LINKED ISSUE #500: [RFE] dump tracebacks to the log
It would be nice to have tracebacks in the log file so they aren't so ephemeral. It would also be nice to turn off dumping tracebacks back to the client.

### PR DESCRIPTION
**Pull request by ronichoudhury**
This causes Tangelo to log the traceback whenever a service module can't be imported (it was already reporting when the service could not be run).

Closes #500

### CODE REVIEW

**Comment by ronichoudhury** [comment]
@mathstuf, @bradking, this should address your concerns.

I will do a live demo of it for @mathstuf when he's free.

**Comment by mathstuf** [comment]
The traceback is now in the logs, but still goes to the client, so it is an improvement.

**Comment by ronichoudhury** [comment]
@mathstuf pointed out that sending the error traceback to the client may constitute a security issue.  Instead, we could report a unique, random tag to the user, along with a general error message, and tag the traceback in the log with the same random tag.  This way, the user can identify the traceback uniquely to the site administrator without being able to actually see it.

@jeffbaumes what do you think?

**Comment by ronichoudhury** [comment]
I have opened #503 in re my previous comment.

**Comment by jeffbaumes** [comment]
Seems reasonable enough. Something like "If this problem persists, contact your site administrator and reference the error code: FJRI43FE9".

**Pull request merged**
