### PR TITLE
Enable verbosity.

### PR DESCRIPTION
**Pull request by manthey**
Hithertofore, the verbosity option did nothing.  We now default to a log level of INFO, and adding --verbose or -v increases the log level.  Adding --quiet or -q decreases the log level.  Added a tangelo.log_debug method, and tangelo.log can have a lvl specified.

### CODE REVIEW

**Comment by ronichoudhury** [comment]
@manthey do these logging levels form an inclusiveness hierarchy?  How does it work?  For instance, I generally want to see the "Tangelo is running" message on the log when I launch Tangelo, to ensure at a glance that I didn't attempt to use the wrong port, etc.  In the default case, will I see those "success" messages?

**Comment by manthey** [comment]
Yes.

Tangelo uses cherrypy, which uses python logs and log levels.  Cherrypy has two sets of logs, access_log which logs URLs that get served, and error_log which logs anything else.  tangelo.log logs to the cherrypy error_log.

Since this uses the Python logging module under the hood, the log levels are specified here: https://docs.python.org/2/library/logging.html#logging-levels .  You can set the log level of a log handler, and then any message with a log level equal to or greater than the handler's log level will actually be logged.

Therefore, if the log is logged as `logging.WARNING` (== 30), it will show up if the log level (our verbosity) is set to any value <= 30, and not be printed if the value > 30.

I picked some log levels for the different tangelo.log_* methods that I thought made sense.  Simply, if you run tangelo without any specification, you'll get the same messages now as you did before.  `tangelo -q` will pretty much only print 'TANGELO Server is running' and 'TANGELO Be seeing you.', plus whatever the plugins cause.  `tangelo -qq` will probably be completely silent unless there are errors.  `tangelo -v` currently doesn't print more than `tangelo`, but we can add `tangelo.log_debug()` calls which wouldn't show without it.

**Comment by ronichoudhury** [comment]
Very cool.  Let me poke around a bit with this before I sign off on it.
Thanks @manthey!

**Comment by ronichoudhury** [comment]
I like this a lot.  I'm going to reconfigure the existing log functions a bit and fill in a few for the other named log levels.  I like defaulting the level to ``INFO`` but I'm going to basically get rid of the ``log_success()`` function, which I think doesn't make too much sense.

**Comment by ronichoudhury** [comment]
@manthey please take a look and let me know if there are any glaring problems with my commits.  Thanks!

**Comment by ronichoudhury** [comment]
I made a few changes.  @manthey, please let me know if they LGTY.

- Got rid of ``log_success()`` since "success" is not a standard log level - we were only using it for messages that are just as well handled by ``log_info()`` anyway
- Added a ``log_critical()`` function to match up with that standard log level
- Changed the colors around a little:
    - debug gets a bold blue - this is to set it off easily from surrounding text
    - info is purple (no change here) - an unassuming, pleasant color
    - warning is yellow (not bold anymore) - I had been using this level for debugging, but now that we have ``log_debug()`` we don't need this to be bold anymore
    - error is red
    - critical gets a bold, bright red
- The errors early in startup about, e.g., incompatible command line arguments, are now treated as critical errors
- The "started up" and "shut down" messages are now printed in a one-off green color.  This is so you can verify at a(n even quicker) glance that Tangelo has started up properly.  These are also now INFO messages, so they will not show up with ``-q``.
- The core no longer uses any bare ``log()`` calls - all such calls were turned into ``log_info()`` calls
- Recast the new tests in light of the changes above

**Comment by manthey** [comment]
Your changes LGTM.

**Pull request merged**
