### PR TITLE
GeoJS update

### PR DESCRIPTION
**Pull request by ronichoudhury**

### CODE REVIEW

**Comment by ronichoudhury** [comment]
@jeffbaumes could you sanity check this one as well?

**Comment by jeffbaumes** [comment]
Will do

**Comment by jeffbaumes** [comment]
This is unrelated to this branch, but I get the following when running grunt and cannot QA this branch:

```
Running "install" task
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing ./sdist/tangelo-0.9.0.dev0.tar.gz
Collecting cherrypy<4.0,>=3.2 (from tangelo==0.9.0.dev0)
Collecting PyYAML==3.11 (from tangelo==0.9.0.dev0)
Collecting ws4py==0.3.2 (from tangelo==0.9.0.dev0)
Building wheels for collected packages: tangelo
Exception:
Traceback (most recent call last):
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/pip/commands/install.py", line 293, in run
    wb.build(autobuilding=True)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/pip/wheel.py", line 756, in build
    ensure_dir(output_dir)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/pip/utils/__init__.py", line 70, in ensure_dir
    os.makedirs(path)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/jeff/Library/Caches/pip/wheels/a2/69'

Warning: Could not install Tangelo to virtual environment:
 Use --force to continue.

Aborted due to warnings.
```

**Comment by ronichoudhury** [comment]
Does this happen on the develop branch as well?

**Comment by ronichoudhury** [comment]
Could it be related to [this](https://github.com/pypa/pip/issues/2970)?

**Comment by jeffbaumes** [comment]
I was able to clean up my cache directory and retry - something with elevated permissions somehow ended up there.

**Comment by jeffbaumes** [comment]
Flickr example has a few issues:

 * The instructions say to do `pip install pymongo` but this installs a new version that is incompatible with the pymongo used in the flickr demo:

```
[22/Sep/2015:11:26:55] SERVICE Could not execute service /plugin/mongo/mongo/localhost/tangelo/flickr_paris:
Traceback (most recent call last):
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/tangelo/server.py", line 448, in invoke_service
    result = service.run(*pargs, **kwargs)
  File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/tangelo/pkgdata/plugin/mongo/web/mongo.py", line 56, in run
    c = pymongo.Connection(server)[db][coll]
AttributeError: 'module' object has no attribute 'Connection'
```

 * The link to the data is broken, should be http://midas3.kitware.com/midas/download/item/315558/flickr_paris.json but is currently http://midas3.kitwarein.com/midas/download/item/315558/flickr_paris.json

**Comment by ronichoudhury** [comment]
On Tue, Sep 22, 2015 at 11:29 AM Jeffrey Baumes <notifications@github.com>
wrote:

>
>    - The instructions say to do pip install pymongo but this installs a
>    new version that is incompatible with the pymongo used in the flickr demo:
>
> [22/Sep/2015:11:26:55] SERVICE Could not execute service /plugin/mongo/mongo/localhost/tangelo/flickr_paris:
> Traceback (most recent call last):
>   File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/tangelo/server.py", line 448, in invoke_service
>     result = service.run(*pargs, **kwargs)
>   File "/Users/jeff/code/tangelo/venv/lib/python2.7/site-packages/tangelo/pkgdata/plugin/mongo/web/mongo.py", line 56, in run
>     c = pymongo.Connection(server)[db][coll]
> AttributeError: 'module' object has no attribute 'Connection'
>
> Between updating the code to make use of a modern pymongo, and telling the
user to install an older pymongo, I prefer the former because installing an
old pymongo will fail for the majority of users (since they'll likely have
a newer one installed already, especially if they are Tangelo users).


>    - The link to the data is broken, should be
>    http://midas3.kitware.com/midas/download/item/315558/flickr_paris.json
>    but is currently
>    http://midas3.kitwarein.com/midas/download/item/315558/flickr_paris.json
>
> Maybe we should go whole hog and move this data to data.kitware.com?

Thoughts?

>

**Comment by jeffbaumes** [comment]
+1 for both suggestions. This branch LGTM if you want to separate these out into another issue or issues.

**Comment by ronichoudhury** [comment]
Thanks, will do!

**Comment by ronichoudhury** [comment]
Opened #520 and #521 to track remaining issues with this branch.

**Pull request merged**
